<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?=SITE_LOC?>">TRPO Lab</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li><a href="<?=SITE_LOC?>">Главная</a></li>
                    <?php if (UserRights::isAdmin(User::getInstance())):?>
                    <li><a href="<?=SITE_LOC?>/admin">Админпанель</a></li>
                    <?php endif?>
                    <?php if (UserRights::isUser(User::getInstance()) || UserRights::isKladovschik(User::getInstance())):?>
                    <li><a href="<?=SITE_LOC?>/goods">Товары</a></li>
                    <?php endif?>
                    <?php if (UserRights::isPostavshchik(User::getInstance())):?>
                    <li><a href="<?=SITE_LOC?>/requests">Поставки</a></li>
                    <?php endif?>
                </ul>
            </div>
        </div>
    </div>
</div>